name: CaughtTheLodestone
main: lenlenlL6\caughttlodestone\Main
author: [lenlenlL6]
api: 5.0.0
version: 1.0.0

permissions:
  ctl.command.games:
    description: /ctl
    default: true
  ctl.command.edit:
    description: /ctle
    default: op